### ISSUE TITLE
Request for a More Comprehensive and Updated README

### ISSUE THREAD

**Issue by hoklims** [Trameurs/DofusFashionistaVanced#1]
I am writing to request an update to the project's README file. I have attempted to set up the project in the past and faced some challenges, which I believe could be mitigated with a more comprehensive and up-to-date guide.

Issues Faced
While I won't go into the specifics of the issues here, I'd like to point out that they are similar to those faced in the original project. A clearer README could help new contributors like myself get started more easily.

Suggested Improvements
A step-by-step guide for setting up the project
Troubleshooting section for common issues
Updated dependencies and their versions
Examples of how to use the project

**Comment by hoklims** [comment]
Thank you for your reply, I'm looking forward to the rest. Thank you so much for keeping this project going!

**Comment by ivanmviveros** [comment]
hello @Trameurs,

I would like to contribute a little to this project, I have some experience in django projects as well as in dockerizing them, so I could help in the configuration for development and deployment of the project using docker, which could help facilitate contributions to the project , since it could be installed without much effort after cloning the repository, but until now I have had problems setting up the project. I'm waiting for the most updated readme to see if it solves the initial installation and configuration problems and then advances in dockerization.

**Comment by Trameurs** [comment]
Hello @ivanmviveros 

I'm almost done with the revival of fashionista, it is fully working and updated to the latest version of Dofus.
I still have to add all languages for new items (now they are only in English), special effects for new and old items (like the Dofus/legendary effects), add images for new items and some other details.
Not giving a date yet as I don't know how much free time I'll have to finish up, but should be close maybe a couple weeks to be sure everything is up and ready.

I'll update the readme after I fully finish with the website, for now I'm still able to figure out how to continue, it's not easy but I'm getting there.

Also I saw you made an api for Dofus, the scrapper in the fashionista project use Dofus Encyclopedia, but it's very broken with a lot of missing items 
Random example : https://www.dofus.com/en/mmorpg/encyclopedia/equipment/15699-belteen
Which mean I have to add these by hand for now and I'll probably miss some, maybe using your api in the future might be a good idea for faster and more reliable updates.

_Sorry for closing the issue again, I keep clicking on it thinking it's a drop down menu lol_

**Comment by ivanmviveros** [comment]
> Hello @ivanmviveros
> 
> I'm almost done with the revival of fashionista, it is fully working and updated to the latest version of Dofus. I still have to add all languages for new items (now they are only in English), special effects for new and old items (like the Dofus/legendary effects), add images for new items and some other details. Not giving a date yet as I don't know how much free time I'll have to finish up, but should be close maybe a couple weeks to be sure everything is up and ready.
> 
> I'll update the readme after I fully finish with the website, for now I'm still able to figure out how to continue, it's not easy but I'm getting there.
> 
> Also I saw you made an api for Dofus, the scrapper in the fashionista project use Dofus Encyclopedia, but it's very broken with a lot of missing items Random example : https://www.dofus.com/en/mmorpg/encyclopedia/equipment/15699-belteen Which mean I have to add these by hand for now and I'll probably miss some, maybe using your api in the future might be a good idea for faster and more reliable updates.
> 
> _Sorry for closing the issue again, I keep clicking on it thinking it's a drop down menu lol_

That's great, I hope we can see the project up and running again soon. About the api, it could definitely be a good way to replace scrapper, but, my api repository is just a fork and I don't have any credit for its implementation, the original is https://github.com/dofusdude/doduapi. I have only used the api, but I think I could help with changing the scrapper

**Comment by Trameurs** [comment]
@ivanmviveros @hoklims 
Website is up and running :) 
https://fashionistavanced.com/
